"""init

Revision ID: 1882a22193a9
Revises: 
Create Date: 2021-01-27 18:39:48.358171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1882a22193a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=55), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('is_wiki_has', sa.Boolean(), nullable=True),
    sa.Column('is_disambiguation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    op.drop_table('texts')
    # ### end Alembic commands ###
